#!/bin/bash
# kasutaja lisamise skript
if [ $# -ne 1 ]; then
  echo "Kasutusjuhend: $0 kasutajanimi"
  exit 1
else
  kasutajanimi=$1
  useradd $kasutajanimi -m -s /bin/bash
  kasu_tulemus=$?

  passwd -d $kasutajanimi >/dev/null 2>&1 || true

  if [ $kasu_tulemus -eq 0 ]; then
    echo "Kasutaja nimega $kasutajanimi on lisatud süsteemi"
    echo "----- /etc/passwd rida -----"
    grep "^$kasutajanimi:" /etc/passwd
    echo "----- kodukataloogi sisu -----"
    ls -la /home/$kasutajanimi
  else
    echo "Probleem kasutaja $kasutajanimi lisamisega"
    echo "Probleemi kood on $kasu_tulemus"
  fi
fi
